# Generated by Django 5.2.6 on 2025-09-16 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('bar', 'Бар'), ('park', 'Парк'), ('museum', 'Музей'), ('cinema', 'Кінотеатр'), ('other', 'Інше')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='places_app/default.jpg', upload_to='places_app/')),
            ],
        ),
    ]
